apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-1-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-client
  
  nfs:
    server: 10.0.3.1
    path: /mnt/user/kube_storage/python-sample-app
  
  
  