apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-7685-pvc
  labels:
    app: test-7685
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  volumeName: test-7685-pv