apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tets
  namespace: argocd
  labels:
    app: tets
  annotations: 
    # argocd-image-updater.argoproj.io/write-back-method: kustomization
    # argocd-image-updater.argoproj.io/git-branch: main
    # argocd-image-updater.argoproj.io/image-list: python-sample-app
spec:
  project: infra
  source:
    repoURL: https://github.com/jamesatintegratnio/backstage-test-repo
    targetRevision: HEAD
    path: apps/testetsetset/tets
  destination:
    name: in-cluster
    namespace: testetsetset
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true