apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tets-pvc
  labels:
    app: tets
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  volumeName: tets-pv