apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-4235234
  namespace: argocd
  labels:
    app: test-4235234
  annotations: 
    # argocd-image-updater.argoproj.io/write-back-method: kustomization
    # argocd-image-updater.argoproj.io/git-branch: main
    # argocd-image-updater.argoproj.io/image-list: python-sample-app
spec:
  project: infra
  source:
    repoURL: https://github.com/jamesatintegratnio/backstage-test-repo
    targetRevision: HEAD
    path: apps/test-124812/test-4235234
  destination:
    name: in-cluster
    namespace: test-124812
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true