apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-4235234-pvc
  labels:
    app: test-4235234
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  volumeName: test-4235234-pv