apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: AskRegen-pvc
  labels:
    app: AskRegen
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  volumeName: AskRegen-pv