apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-1-pv
  labels:
    app: demo-1
  annotations:
    pv.kubernetes.io/provisioned-by: k8s-sigs.io/nfs-subdir-external-provisioner
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-client
  
  nfs:
    server: 10.0.0.12
    path: /mnt/user/kube_storage/demo-1
  
  
  