apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-3
  namespace: argocd
  labels:
    app: demo-3
  annotations: 
    # argocd-image-updater.argoproj.io/write-back-method: kustomization
    # argocd-image-updater.argoproj.io/git-branch: main
    # argocd-image-updater.argoproj.io/image-list: python-sample-app
spec:
  project: infra
  source:
    repoURL: github.com?owner=jamesatintegratnio&repo=backstage-test-repo
    targetRevision: HEAD
    path: apps/demo-3/demo-3
  destination:
    name: in-cluster
    namespace: demo-3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true