apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-3-pv
  labels:
    app: demo-3
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs-client
  
  nfs:
    server: 10.0.0.12
    path: /mnt/user/kube_storage/python-sample-app
  
  
  