apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-3-pvc
  labels:
    app: demo-3
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  volumeName: demo-3-pv