apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-2
  namespace: argocd
  labels:
    app: demo-2
  annotations: 
    # argocd-image-updater.argoproj.io/write-back-method: kustomization
    # argocd-image-updater.argoproj.io/git-branch: main
    # argocd-image-updater.argoproj.io/image-list: python-sample-app
spec:
  project: infra
  source:
    repoURL: 
    targetRevision: HEAD
    path: apps/demo-2/demo-2
  destination:
    name: in-cluster
    namespace: demo-2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true