apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-2
  labels:
    app: demo-2
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: demo-2
    backstage.io/kubernetes-label-selector: app=demo-2
    argocd/app-name: demo-2
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
